### PR TITLE
Fix: Snapcraft issue 

### PR DESCRIPTION
**Pull request by SamirPS**
This PR solve error when using snapcraft to build the snap. Using core20 as a base and the plugin go.

Solve issue #156 

Signed-Off-By: Samir Akarioh <samir.akarioh@canonical.com>

### CODE REVIEW

**Comment by SamirPS** [comment]
@mvo5 a small ping

**Comment by mvo5** [comment]
Hey @SamirPS - thanks for your PR - could you please check https://github.com/snapcore/spread/pull/132 and see if that works for you too? If so I will talk to Gustavo to get things merged.

**Comment by SamirPS** [comment]
Hey @mvo5, this PR looks good to me

**Comment by mvo5** [comment]
Closing in favor of the now merged https://github.com/snapcore/spread/pull/132

**Pull request closed without merging**
